name: BE ETL Automation Tests

env:
  exp_key_default: "TestData/SCIP7-SN0010ZMS204100004/001155_20220107_000523"
  post_to_jira: false

on:
  workflow_dispatch:
    inputs:
      exp_key:
        description: 'S3 object path within S3 bucket qa-workbench-data-lake e.g. Data/SCIP-XYZABC/TEST-NUM_DATE_TIME'
        required: true
        default: 'TestData/SCIP7-SN0010ZMS204100004/001155_20220107_000523'
      post_to_jira:
        description: 'Post results to jira?'
        required: true
        default: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "exp_key is ${{ github.event.inputs.exp_key }}"
          echo "post_to_jira is ${{ github.event.inputs.post_to_jira || env.post_to_jira }}"
          echo "The result of this expression is ${{ ( github.events.inputs.post_to_jira || env.post_to_jira ) == true }}"

      - name: test post to jira
        if: ${{ ( github.events.inputs.post_to_jira || env.post_to_jira ) == true }}
        run: |
          echo "Post to jira is true"
