name: BE ETL Automation Tests

env:
  exp_key_default: "TestData/SCIP7-SN0010ZMS204100004/001155_20220107_000523"
  post_to_jira_env: false

on:
  workflow_dispatch:
    inputs:
      exp_key:
        description: 'S3 object path within S3 bucket qa-workbench-data-lake e.g. Data/SCIP-XYZABC/TEST-NUM_DATE_TIME'
        required: true
        default: 'TestData/SCIP7-SN0010ZMS204100004/001155_20220107_000523'
      post_to_jira:
        description: 'Post results to jira?'
        required: true
        default: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test post to jira input
        if: github.events.inputs.post_to_jira
        run: |
          echo "Post to jira input"
      
      - name: test post to jira environment variable
        if: env.post_to_jira_env
        run: |
          echo "Post to jira environment variable"
  
      - name: test post to jira environment variable
        if: github.events.inputs.post_to_jira || env.post_to_jira_env
        run: |
          echo "Post to jira or statement"
